### PR TITLE
Fixed #82 [Pie+] timer crashes when page not in foreground

### LINKED ISSUE #82: [Oreo+] timer crashes when page not in foreground
User report:

> After setting and starting the timer, if I try to leave the timer page, the app crashes and the timer therefore stops. Timer works fine if I stay on the timer page. Samsung s10+, stock Android 9.

Likely a background restriction problem. Need to do some testing / debugging to try and reproduce the issue myself.

### PR DESCRIPTION
**Pull request by Nulide**
This should fix the bug.
It's caused by the RecyclerView holding both the alarms and the timers.
When accessing the alarms the size of timers need to be subtracted so you don't reach OutOfBounnce.

### CODE REVIEW

File: app/src/main/java/me/jfenn/alarmio/adapters/AlarmsAdapter.kt [hunk 1]
```diff
@@ -447,8 +448,7 @@ class AlarmsAdapter(private val alarmio: Alarmio, private val recycler: Recycler
                 }
 
                 override fun afterTextChanged(editable: Editable) {
-                    if (name.hasFocus()) // ignore .setText() calls
-                        alarms.getOrNull(adapterPosition)?.setName(alarmio, editable.toString())
+                    alarms[adapterPosition-timers.size].setName(alarmio, editable.toString())
```
Comment (fennifith) [inline app/src/main/java/me/jfenn/alarmio/adapters/AlarmsAdapter.kt:451]: Good catch! I definitely missed this problem before.

I would still stick to null-safety here, and the `name.hasFocus()` check is important to prevent the adapter's own `.setText()` calls from invoking it - although it looks like you were initially working off the `master` branch, so you may have missed these changes :)

```suggestion
                    if (name.hasFocus()) // ignore .setText() calls
                        alarms.getOrNull(adapterPosition-timers.size)?.setName(alarmio, editable.toString())
```

**Comment by fennifith** [comment]
Thanks for contributing! I'll add another commit here to add your username to the README before merging - feel free to edit it & create another PR if you want.
